### Libraries

In [3]:
import numpy as np
import soundfile as sf
import librosa

### Decoding of B-format signals (placing virtual microphones)

In [ ]:
# kappa.m
# Author: V. Pulkki, T. Lokki
# Simple example of cardioid decoding of B-format signals
#
#--------------------------------------------------------------------------
# This source code is provided without any warranties as published in 
# DAFX book 2nd edition, copyright Wiley & Sons 2011, available at 
# http://www.dafx.de. It may be used for educational purposes and not 
# for commercial applications without further permission.
#--------------------------------------------------------------------------

pi = np.pi
# mono signal
signal, Fs = librosa.load('doorbell-sound-effect.wav',sr=None)
# Simulated horizontal-only B-format recording of single 
# sound source in direction of theta azimuth.
# This can be replaced with a real B-format recording. 
theta=30
w = signal/(2**(1/2))
x = signal*np.cos(theta/180*pi)
y = signal*np.sin(theta/180*pi)
# Virtual microphone directions 
# (In many cases the values equal to the directions of loudspeakers)
ls_dir = np.array([30, 90, 150, -150, -90, -30])
ls_dir = ls_dir/180
ls_dir = ls_dir*pi
ls_num = ls_dir.size
# Compute virtual cardioids (kappa = 1) out of the B-format signal
kappa=1
LSsignal = np.zeros((signal.size, ls_num))
for i in range(ls_num):
    LSsignal[:,i] = (2-kappa)/2*w + kappa/(2*(2**(1/2)))*(np.cos(ls_dir[i])*x+np.sin(ls_dir[i])*y)
    
# File output
sf.write('firstorderB-formatexample.wav',LSsignal,Fs,'PCM_16')

In [4]:
print(np.array([[1, 2, 6], [2, 3, 6], [3, 4, 7], [4, 5, 8], [5, 1, 8], [1, 6, 8], [3, 6, 7], [4, 7, 8], [6, 7, 8]])- 1)

[[0 1 5]
 [1 2 5]
 [2 3 6]
 [3 4 7]
 [4 0 7]
 [0 5 7]
 [2 5 6]
 [3 6 7]
 [5 6 7]]
